//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpTool.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpTool.Languages.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new MobGrade.
        /// </summary>
        internal static string AddMobGrade {
            get {
                return ResourceManager.GetString("AddMobGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angel.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        internal static string AvgPrice {
            get {
                return ResourceManager.GetString("AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points for Buy.
        /// </summary>
        internal static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Item.
        /// </summary>
        internal static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Monster.
        /// </summary>
        internal static string CreateMonster {
            get {
                return ResourceManager.GetString("CreateMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damages.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Damages.
        /// </summary>
        internal static string DamagePerc {
            get {
                return ResourceManager.GetString("DamagePerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string DbHost {
            get {
                return ResourceManager.GetString("DbHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DbPassword {
            get {
                return ResourceManager.GetString("DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Username.
        /// </summary>
        internal static string DbUser {
            get {
                return ResourceManager.GetString("DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all effects.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon.
        /// </summary>
        internal static string Demon {
            get {
                return ResourceManager.GetString("Demon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect :.
        /// </summary>
        internal static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creditentials for the Database was wrong.
        /// </summary>
        internal static string Error_DbCredConnection {
            get {
                return ResourceManager.GetString("Error_DbCredConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Stats.
        /// </summary>
        internal static string GenerateStats {
            get {
                return ResourceManager.GetString("GenerateStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a Boss ?.
        /// </summary>
        internal static string IsBoss {
            get {
                return ResourceManager.GetString("IsBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Summonable ?.
        /// </summary>
        internal static string IsSummonable {
            get {
                return ResourceManager.GetString("IsSummonable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the item.
        /// </summary>
        internal static string ItemCreateError {
            get {
                return ResourceManager.GetString("ItemCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Set Id (-1 if none ItemSet).
        /// </summary>
        internal static string ItemSetId {
            get {
                return ResourceManager.GetString("ItemSetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Stats.
        /// </summary>
        internal static string ItemStats {
            get {
                return ResourceManager.GetString("ItemStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value (0 if fix) :.
        /// </summary>
        internal static string JetMax {
            get {
                return ResourceManager.GetString("JetMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value :.
        /// </summary>
        internal static string JetMin {
            get {
                return ResourceManager.GetString("JetMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Grade.
        /// </summary>
        internal static string NewGrade {
            get {
                return ResourceManager.GetString("NewGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPrice.
        /// </summary>
        internal static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first configured the connection to the Database.
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string Pods {
            get {
                return ResourceManager.GetString("Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string Sagesse {
            get {
                return ResourceManager.GetString("Sagesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string Soins {
            get {
                return ResourceManager.GetString("Soins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatsCreator.
        /// </summary>
        internal static string StatsCreator {
            get {
                return ResourceManager.GetString("StatsCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Successfully connected !.
        /// </summary>
        internal static string Success_DbConnect {
            get {
                return ResourceManager.GetString("Success_DbConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summable Creatures.
        /// </summary>
        internal static string SummonCrea {
            get {
                return ResourceManager.GetString("SummonCrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Infos.
        /// </summary>
        internal static string WeaponInfo {
            get {
                return ResourceManager.GetString("WeaponInfo", resourceCulture);
            }
        }
    }
}
